[tool.poetry]
name = "tesseract"
version = "0.1.0"
description = ""
authors = ["Pavel Milanov <milanov71@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pymupdf = "^1.22.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
