version: '3.9'

services:
  backend:
    build:
      context: ./backend/backend
    container_name: backend
    command: supervisord -c supervisord.conf
    restart: always
    env_file:
      - ./.config.env
    depends_on:
      - postgres
      - redis
    volumes:
      - server_logs:/server/logs
      - acts:/server/files/acts
    healthcheck:
      test: curl --fail http://localhost:8000/check || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - application

  frontend:
    build:
      context: ./web
      args:
        - listen_ip=0.0.0.0
        - version=v0.0.0
    container_name: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - acts:/files/acts
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - application
    ports:
      - 80:80

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file:
      - ./.config.env
    volumes:
      - db:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - application

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - cache:/data
    healthcheck:
      test: redis-cli ping | grep PONG || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - application

networks:
  application:

volumes:
  cache:
  db:
  server_logs:
  acts:
